### PR TITLE
Add no_std support.

### PR DESCRIPTION
**Pull request by jeandudey**
- Renamed the "nostd" feature to "std" in order to follow the convention with most crates and to avoid any crate specifying the "nostd" feature as another crate might want "std" collections but it was disabled by the other crate.

- Added an "alloc" feature in order to support no_std but additionally alloc structures.

- Separated implementation modules for both "std" and "alloc".

Testing can be done as:

```bash
cargo build --no-default-features

cargo build --no-default-features --features "alloc"

cargo build
```

### CODE REVIEW

**Comment by timothee-haudebourg** [comment]
That's great. The `nostd` feature was a bad idea, features are supposed to be additive. Can you just rebase over the recent changes of the `master` branch? I've added a CI file. Please also add a test in the CI without the `std` feature.

**Comment by jeandudey** [comment]
@timothee-haudebourg rebased

**Comment by timothee-haudebourg** [comment]
Great! Now can you add an entry to the `test` job in `.github/workflows/ci.yml` so it can test without default features? Something like:
```yml
- name: Test (no default features)
      run: cargo test --no-default-features --verbose
```
Just want to make sure that futures changes do not improperly rely on the `std` or `alloc` features.

**Comment by jeandudey** [comment]
Added it and fixed the example and the doc test to build with and without default features enabled

**Comment by jeandudey** [comment]
Thanks!

**Pull request merged**
